export default (params) => {
    const { length } = params;
    const item = {
      "id": 1323546,
      "uuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
      "planUuid": "1EDAO8HO705T0B131EAC000007F3CFABD0",
      "planName": "广州市区",
      "customerId": 835396698234,
      "deptId": 0,
      "deptName": null,
      "employeeId": 98032121,
      "period": "202008",
      "employeeNumber": "",
      "name": "0RQuJ75gxCUu2HG5i2xSwQ==",
      "licenseNumber": "8As4nrlJwKedFhHEPyQQPYpvPeP8mdFGlGbPNkFo7Cs=",
      "state": "正常参保",
      "companySocialInsuranceAmount": 12558,
      "personalSocialInsuranceAmount": 13564,
      "companyHousingFundAmount": 0,
      "personalHousingFundAmount": 0,
      "totalAmount": 26122,
      "insuranceDetailList": [
          {
              "detailId": 6167350,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "基本养老保险",
              "itemType": "SOCIAL_INSURANCE",
              "radix": 12321,
              "companyRatio": 0,
              "personalRatio": 0,
              "companyFixedAmount": 0,
              "personalFixedAmount": 0,
              "companyAmount": 12312,
              "personalAmount": 12,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167351,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "基本医疗保险",
              "itemType": "SOCIAL_INSURANCE",
              "radix": 123,
              "companyRatio": 0,
              "personalRatio": 0,
              "companyFixedAmount": 0,
              "personalFixedAmount": 0,
              "companyAmount": 123,
              "personalAmount": 12321,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167352,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "失业保险",
              "itemType": "SOCIAL_INSURANCE",
              "radix": 21111,
              "companyRatio": 0,
              "personalRatio": 0,
              "companyFixedAmount": 0,
              "personalFixedAmount": 0,
              "companyAmount": 123,
              "personalAmount": 1231,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167353,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "工伤保险",
              "itemType": "SOCIAL_INSURANCE",
              "radix": 12321,
              "companyRatio": 0,
              "personalRatio": null,
              "companyFixedAmount": 0,
              "personalFixedAmount": null,
              "companyAmount": 0,
              "personalAmount": null,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167353,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "生育保险",
              "itemType": "SOCIAL_INSURANCE",
              "radix": 12321,
              "companyRatio": 0,
              "personalRatio": null,
              "companyFixedAmount": 0,
              "personalFixedAmount": null,
              "companyAmount": 0,
              "personalAmount": null,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167354,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "住房公积金",
              "itemType": "HOUSING_FUND",
              "radix": 0,
              "companyRatio": 0,
              "personalRatio": 0,
              "companyFixedAmount": 0,
              "personalFixedAmount": 0,
              "companyAmount": 0,
              "personalAmount": 0,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167355,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "补充住房公积金",
              "itemType": "HOUSING_FUND",
              "radix": 0,
              "companyRatio": 0,
              "personalRatio": 0,
              "companyFixedAmount": 0,
              "personalFixedAmount": 0,
              "companyAmount": 0,
              "personalAmount": 0,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          },
          {
              "detailId": 6167356,
              "insuranceUuid": "1EFT3IGBP02O0B3C1EAC000001B961F010",
              "customerId": 835396698234,
              "deptId": 0,
              "period": "202008",
              "employeeId": 98032121,
              "itemName": "住房补贴利息津贴",
              "itemType": "HOUSING_FUND",
              "radix": 0,
              "companyRatio": 0,
              "personalRatio": 0,
              "companyFixedAmount": 0,
              "personalFixedAmount": 0,
              "companyAmount": 0,
              "personalAmount": 0,
              "companyRoundingMode": "HALF_UP_TO_FEN",
              "personalRoundingMode": "HALF_UP_TO_FEN"
          }
      ]
    };
    const massList = [];
    for(let i = 0 ; i < length ; i++ ){
      massList.push({
        ...item,
        "id": Math.floor(Math.random() * 10000),
        "uuid": Math.floor(Math.random() * 1000000),
        "planUuid": Math.floor(Math.random() * 1000000),
        "planName": "广州市区" + i,
        "customerId": Math.floor(Math.random() * 10000),
        "employeeId": Math.floor(Math.random() * 10000),
      })
    }
    return {
      "list": massList,
      "total": length,
      "insuranceItemSumList": [
          {
              "itemType": "HOUSING_FUND",
              "itemName": "住房公积金",
              "countRadix": 0,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 0,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 0
          },
          {
              "itemType": "HOUSING_FUND",
              "itemName": "补充住房公积金",
              "countRadix": 0,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 0,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 0
          },
          {
              "itemType": "HOUSING_FUND",
              "itemName": "住房补贴利息津贴",
              "countRadix": 0,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 0,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 0
          },
          {
              "itemType": "SOCIAL_INSURANCE",
              "itemName": "基本养老保险",
              "countRadix": 24855,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 24747,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 3234
          },
          {
              "itemType": "SOCIAL_INSURANCE",
              "itemName": "基本医疗保险",
              "countRadix": 246,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 246,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 24642
          },
          {
              "itemType": "SOCIAL_INSURANCE",
              "itemName": "失业保险",
              "countRadix": 153228,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 7153.04,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 3448.72
          },
          {
              "itemType": "SOCIAL_INSURANCE",
              "itemName": "工伤保险",
              "countRadix": 408648,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 986.72,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 0
          },
          {
              "itemType": "SOCIAL_INSURANCE",
              "itemName": "生育保险",
              "countRadix": 423006,
              "countCompanyFixedAmount": 0,
              "countCompanyAmount": 986.72,
              "countPersonalFixedAmount": 0,
              "countPersonalAmount": 0
          }
      ]
    }
}